CREATE TABLE PESSOA (ID BIGINT NOT NULL, CPF VARCHAR(255), PRIMEIRONOME VARCHAR(255), ULTIMONOME VARCHAR(255), PRIMARY KEY (ID))
CREATE TABLE SEQUENCE (SEQ_NAME VARCHAR(50) NOT NULL, SEQ_COUNT DECIMAL(15), PRIMARY KEY (SEQ_NAME))
INSERT INTO SEQUENCE(SEQ_NAME, SEQ_COUNT) values ('SEQ_GEN', 0)
